name: clang-format check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'bin'
    steps:
    - name: Setup GitHub actions
      uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '16'
        check-path: ${{ matrix.path }}
